### ISSUE TITLE
Continue on Issue #107 - Error retrieving list of networks on this controller: HTTPError: Response code 401 (Unauthorized)

### ISSUE THREAD

**Issue by angyen** [key-networks/ztncui#114]
Good day.

After I input the commands:-
`
sudo -i
echo ZT_TOKEN=`cat /var/lib/zerotier-one/authtoken.secret` >> /opt/key-networks/ztncui/.env
chmod 400 /opt/key-networks/ztncui/.env
chown ztncui.ztncui /opt/key-networks/ztncui/.env
systemctl restart ztncui
`
I am able to login again but when I go to "networks" tab, I am not able to see my existing networks.
The following message is shown:

Error retrieving list of networks on this controller: HTTPError: Response code 401 (Unauthorized)

May I know how to resolve this?

**Comment by angyen** [comment]
May I know if you could assist on this?

**Comment by taich001** [comment]
I fixed this with a bash script that will run every two minutes.

**Comment by angyen** [comment]
> 

Could you share the bash script and how to apply it?

Thank you in advance.

**Comment by key-networks** [comment]
Did you execute exactly as per the instructions at https://key-networks.com/ztncui
```
sudo sh -c "echo ZT_TOKEN=`sudo cat /var/lib/zerotier-one/authtoken.secret` > /opt/key-networks/ztncui/.env"
```
Note the [backticks](https://en.wikipedia.org/wiki/Backtick) around `sudo cat /var/lib/zerotier-one/authtoken.secret`

**Comment by angyen** [comment]
> Did you execute exactly as per the instructions at https://key-networks.com/ztncui
> 
> ```
> sudo sh -c "echo ZT_TOKEN=`sudo cat /var/lib/zerotier-one/authtoken.secret` >> /opt/key-networks/ztncui/.env"
> ```
> 
> Note the [backticks](https://en.wikipedia.org/wiki/Backtick) around `sudo cat /var/lib/zerotier-one/authtoken.secret`

Yes I did.

and I just did it again so to make sure that all the command are entered correctly and the following are the screen shots of various tab after I executed the command for your reference. 

I am still getting the Response code 401.

[https://mptsd-my.sharepoint.com/:i:/g/personal/dr_mptsd_onmicrosoft_com/EctSrVfT9KZFsHtTz-yLPFcB59pZJwo1eN5ObcRBHzyrzA?e=5jEaCO](url)

**Comment by key-networks** [comment]
Do you see a line in `/opt/key-networks/ztncui/.env` like:
`ZT_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXX`
where XXXXXXXXXXXXXXXXXXXXXXXX is the content of `/var/lib/zerotier-one/authtoken.secret`?

Please show the output of:
`ls -l /opt/key-networks/ztncui/.env`

**Comment by key-networks** [comment]
From your screenshot, you are not using backticks.  Instead, you are using single quotes.  Please see https://en.wikipedia.org/wiki/Backtick

**Comment by key-networks** [comment]
Backtick is normally directly under the `esc` key in the top left corner of your keyboard.

**Comment by angyen** [comment]
Thank you so much for pointing out my mistake
It works now after I replaced the quote with backtick.

**Comment by key-networks** [comment]
Great to hear that - thanks for your feedback!

**Comment by taich001** [comment]
Set the ZT_TOKEN in .env worked for me too.
